/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MaliciousAttacker,
  MaliciousAttackerInterface,
} from "../../../contracts/test/MaliciousAttacker";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_victimContract",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "attack",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "stolenFunds",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "victimContract",
    outputs: [
      {
        internalType: "contract AuctionDeposit",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516103c53803806103c583398101604081905261002f91610054565b600080546001600160a01b0319166001600160a01b0392909216919091179055610084565b60006020828403121561006657600080fd5b81516001600160a01b038116811461007d57600080fd5b9392505050565b610332806100936000396000f3fe6080604052600436106100385760003560e01c806310890a87146100dc57806364dd891a14610105578063f32d251d1461012557610057565b3661005757346001600082825461004f91906102a3565b925050819055005b600054670de0b6b3a76400006001600160a01b0390911631106100da57600054604051632e1a7d4d60e01b8152670de0b6b3a764000060048201526001600160a01b0390911690632e1a7d4d90602401600060405180830381600087803b1580156100c157600080fd5b505af11580156100d5573d6000803e3d6000fd5b505050505b005b3480156100e857600080fd5b506100f260015481565b6040519081526020015b60405180910390f35b34801561011157600080fd5b506100da6101203660046102e3565b61015d565b34801561013157600080fd5b50600054610145906001600160a01b031681565b6040516001600160a01b0390911681526020016100fc565b804710156101cb576040517f08c379a000000000000000000000000000000000000000000000000000000000815260206004820152601f60248201527f496e73756666696369656e742062616c616e636520666f722061747461636b00604482015260640160405180910390fd5b6000546040517fb6b55f25000000000000000000000000000000000000000000000000000000008152600481018390526001600160a01b039091169063b6b55f2590602401600060405180830381600087803b15801561022a57600080fd5b505af115801561023e573d6000803e3d6000fd5b5050600054604051632e1a7d4d60e01b8152600481018590526001600160a01b039091169250632e1a7d4d9150602401600060405180830381600087803b15801561028857600080fd5b505af115801561029c573d6000803e3d6000fd5b5050505050565b808201808211156102dd577f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b92915050565b6000602082840312156102f557600080fd5b503591905056fea2646970667358221220a34d39f04f92902d224f1fd53e788eb530145e76479cd4baff588f29caf53d9264736f6c63430008120033";

type MaliciousAttackerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MaliciousAttackerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MaliciousAttacker__factory extends ContractFactory {
  constructor(...args: MaliciousAttackerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _victimContract: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_victimContract, overrides || {});
  }
  override deploy(
    _victimContract: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_victimContract, overrides || {}) as Promise<
      MaliciousAttacker & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MaliciousAttacker__factory {
    return super.connect(runner) as MaliciousAttacker__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MaliciousAttackerInterface {
    return new Interface(_abi) as MaliciousAttackerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MaliciousAttacker {
    return new Contract(address, _abi, runner) as unknown as MaliciousAttacker;
  }
}
