/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IMonoNFT {
  export type ShareOfCommunityTokenStruct = {
    shareHolder: AddressLike;
    shareRatio: BigNumberish;
  };

  export type ShareOfCommunityTokenStructOutput = [
    shareHolder: string,
    shareRatio: bigint
  ] & { shareHolder: string; shareRatio: bigint };

  export type MonoNFTStruct = {
    tokenId: BigNumberish;
    donor: AddressLike;
    expiresDuration: BigNumberish;
    uri: string;
    status: BigNumberish;
    sharesOfCommunityToken: IMonoNFT.ShareOfCommunityTokenStruct[];
  };

  export type MonoNFTStructOutput = [
    tokenId: bigint,
    donor: string,
    expiresDuration: bigint,
    uri: string,
    status: bigint,
    sharesOfCommunityToken: IMonoNFT.ShareOfCommunityTokenStructOutput[]
  ] & {
    tokenId: bigint;
    donor: string;
    expiresDuration: bigint;
    uri: string;
    status: bigint;
    sharesOfCommunityToken: IMonoNFT.ShareOfCommunityTokenStructOutput[];
  };

  export type WinnerStruct = {
    winner: AddressLike;
    price: BigNumberish;
    expires: BigNumberish;
  };

  export type WinnerStructOutput = [
    winner: string,
    price: bigint,
    expires: bigint
  ] & { winner: string; price: bigint; expires: bigint };
}

export interface IMonoNFTInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claim"
      | "confirmWinner"
      | "getHistoryOfWinners"
      | "getNFTs"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "isExpired"
      | "register"
      | "renounceRole"
      | "revokeRole"
      | "setAuctionDepositAddress"
      | "setMembershipNFTAddress"
      | "setUser"
      | "submit"
      | "updateMonoNFTStatus"
      | "userExpires"
      | "userOf"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Claim"
      | "ConfirmWinner"
      | "Register"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "UpdateUser"
  ): EventFragment;

  encodeFunctionData(functionFragment: "claim", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "confirmWinner",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getHistoryOfWinners",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getNFTs", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isExpired",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [
      AddressLike,
      BigNumberish,
      string,
      IMonoNFT.ShareOfCommunityTokenStruct[],
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuctionDepositAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMembershipNFTAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setUser",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMonoNFTStatus",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userExpires",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userOf",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confirmWinner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHistoryOfWinners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getNFTs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isExpired", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAuctionDepositAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMembershipNFTAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setUser", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "submit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateMonoNFTStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userExpires",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userOf", data: BytesLike): Result;
}

export namespace ClaimEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    user: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [tokenId: bigint, user: string, price: bigint];
  export interface OutputObject {
    tokenId: bigint;
    user: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConfirmWinnerEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    winner: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [tokenId: bigint, winner: string, price: bigint];
  export interface OutputObject {
    tokenId: bigint;
    winner: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegisterEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    _monoNFT: IMonoNFT.MonoNFTStruct
  ];
  export type OutputTuple = [
    tokenId: bigint,
    _monoNFT: IMonoNFT.MonoNFTStructOutput
  ];
  export interface OutputObject {
    tokenId: bigint;
    _monoNFT: IMonoNFT.MonoNFTStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateUserEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    user: AddressLike,
    expires: BigNumberish
  ];
  export type OutputTuple = [tokenId: bigint, user: string, expires: bigint];
  export interface OutputObject {
    tokenId: bigint;
    user: string;
    expires: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IMonoNFT extends BaseContract {
  connect(runner?: ContractRunner | null): IMonoNFT;
  waitForDeployment(): Promise<this>;

  interface: IMonoNFTInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claim: TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;

  confirmWinner: TypedContractMethod<
    [winner: AddressLike, tokenId: BigNumberish, price: BigNumberish],
    [void],
    "nonpayable"
  >;

  getHistoryOfWinners: TypedContractMethod<
    [tokenId: BigNumberish],
    [IMonoNFT.WinnerStructOutput[]],
    "view"
  >;

  getNFTs: TypedContractMethod<[], [IMonoNFT.MonoNFTStructOutput[]], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isExpired: TypedContractMethod<[tokenId: BigNumberish], [boolean], "view">;

  register: TypedContractMethod<
    [
      donor: AddressLike,
      expiresDuration: BigNumberish,
      uri: string,
      sharesOfCommunityToken: IMonoNFT.ShareOfCommunityTokenStruct[],
      owner: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setAuctionDepositAddress: TypedContractMethod<
    [_auctionDepositContractAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setMembershipNFTAddress: TypedContractMethod<
    [_membershipNFTAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setUser: TypedContractMethod<
    [tokenId: BigNumberish, user: AddressLike, expires: BigNumberish],
    [void],
    "nonpayable"
  >;

  submit: TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;

  updateMonoNFTStatus: TypedContractMethod<
    [tokenId: BigNumberish, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  userExpires: TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;

  userOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confirmWinner"
  ): TypedContractMethod<
    [winner: AddressLike, tokenId: BigNumberish, price: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getHistoryOfWinners"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [IMonoNFT.WinnerStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNFTs"
  ): TypedContractMethod<[], [IMonoNFT.MonoNFTStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isExpired"
  ): TypedContractMethod<[tokenId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<
    [
      donor: AddressLike,
      expiresDuration: BigNumberish,
      uri: string,
      sharesOfCommunityToken: IMonoNFT.ShareOfCommunityTokenStruct[],
      owner: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAuctionDepositAddress"
  ): TypedContractMethod<
    [_auctionDepositContractAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMembershipNFTAddress"
  ): TypedContractMethod<
    [_membershipNFTAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setUser"
  ): TypedContractMethod<
    [tokenId: BigNumberish, user: AddressLike, expires: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submit"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateMonoNFTStatus"
  ): TypedContractMethod<
    [tokenId: BigNumberish, status: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userExpires"
  ): TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "userOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getEvent(
    key: "Claim"
  ): TypedContractEvent<
    ClaimEvent.InputTuple,
    ClaimEvent.OutputTuple,
    ClaimEvent.OutputObject
  >;
  getEvent(
    key: "ConfirmWinner"
  ): TypedContractEvent<
    ConfirmWinnerEvent.InputTuple,
    ConfirmWinnerEvent.OutputTuple,
    ConfirmWinnerEvent.OutputObject
  >;
  getEvent(
    key: "Register"
  ): TypedContractEvent<
    RegisterEvent.InputTuple,
    RegisterEvent.OutputTuple,
    RegisterEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "UpdateUser"
  ): TypedContractEvent<
    UpdateUserEvent.InputTuple,
    UpdateUserEvent.OutputTuple,
    UpdateUserEvent.OutputObject
  >;

  filters: {
    "Claim(uint256,address,uint256)": TypedContractEvent<
      ClaimEvent.InputTuple,
      ClaimEvent.OutputTuple,
      ClaimEvent.OutputObject
    >;
    Claim: TypedContractEvent<
      ClaimEvent.InputTuple,
      ClaimEvent.OutputTuple,
      ClaimEvent.OutputObject
    >;

    "ConfirmWinner(uint256,address,uint256)": TypedContractEvent<
      ConfirmWinnerEvent.InputTuple,
      ConfirmWinnerEvent.OutputTuple,
      ConfirmWinnerEvent.OutputObject
    >;
    ConfirmWinner: TypedContractEvent<
      ConfirmWinnerEvent.InputTuple,
      ConfirmWinnerEvent.OutputTuple,
      ConfirmWinnerEvent.OutputObject
    >;

    "Register(uint256,tuple)": TypedContractEvent<
      RegisterEvent.InputTuple,
      RegisterEvent.OutputTuple,
      RegisterEvent.OutputObject
    >;
    Register: TypedContractEvent<
      RegisterEvent.InputTuple,
      RegisterEvent.OutputTuple,
      RegisterEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "UpdateUser(uint256,address,uint64)": TypedContractEvent<
      UpdateUserEvent.InputTuple,
      UpdateUserEvent.OutputTuple,
      UpdateUserEvent.OutputObject
    >;
    UpdateUser: TypedContractEvent<
      UpdateUserEvent.InputTuple,
      UpdateUserEvent.OutputTuple,
      UpdateUserEvent.OutputObject
    >;
  };
}
