/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAuctionDeposit } from "./IAuctionDeposit";
export type { IERC4907 } from "./IERC4907";
export type { IERC721Enumerable } from "./IERC721Enumerable";
export type { IMonoNFT } from "./IMonoNFT";
