/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contracts from './contracts'
export type { contracts }
export type { AuctionDeposit } from './contracts/AuctionDeposit'

export type { ERC4907 } from './contracts/erc4907/ERC4907'
export type { IAuctionDeposit } from './contracts/interfaces/IAuctionDeposit'
export type { IERC4907 } from './contracts/interfaces/IERC4907'
export type { IMonoNFT } from './contracts/interfaces/IMonoNFT'
export type { MonoNFT } from './contracts/MonoNFT'
export type { MaliciousAttacker } from './contracts/test/MaliciousAttacker'
export type { MockERC1155 } from './contracts/test/MockERC1155'
export type { MockERC20 } from './contracts/test/MockERC20'
