/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc4907 from "./erc4907";
export type { erc4907 };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as test from "./test";
export type { test };
export type { AuctionDeposit } from "./AuctionDeposit";
export type { MonoNFT } from "./MonoNFT";
